// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/georgg2003/shortener/internal/usecase (interfaces: UseCase)
//
// Generated by this command:
//
//	mockgen -destination ./mock/mock.go -package mock . UseCase
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/georgg2003/shortener/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
	isgomock struct{}
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// DeleteUserURLs mocks base method.
func (m *MockUseCase) DeleteUserURLs(ctx context.Context, urls []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserURLs", ctx, urls)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserURLs indicates an expected call of DeleteUserURLs.
func (mr *MockUseCaseMockRecorder) DeleteUserURLs(ctx, urls any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserURLs", reflect.TypeOf((*MockUseCase)(nil).DeleteUserURLs), ctx, urls)
}

// GetStats mocks base method.
func (m *MockUseCase) GetStats(ctx context.Context) (models.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(models.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockUseCaseMockRecorder) GetStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockUseCase)(nil).GetStats), ctx)
}

// GetUserURLs mocks base method.
func (m *MockUseCase) GetUserURLs(ctx context.Context) ([]models.URLEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserURLs", ctx)
	ret0, _ := ret[0].([]models.URLEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserURLs indicates an expected call of GetUserURLs.
func (mr *MockUseCaseMockRecorder) GetUserURLs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserURLs", reflect.TypeOf((*MockUseCase)(nil).GetUserURLs), ctx)
}

// NewShortURL mocks base method.
func (m *MockUseCase) NewShortURL(ctx context.Context, url string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewShortURL", ctx, url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewShortURL indicates an expected call of NewShortURL.
func (mr *MockUseCaseMockRecorder) NewShortURL(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewShortURL", reflect.TypeOf((*MockUseCase)(nil).NewShortURL), ctx, url)
}

// NewShortURLBatch mocks base method.
func (m *MockUseCase) NewShortURLBatch(ctx context.Context, entities []*models.URLEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewShortURLBatch", ctx, entities)
	ret0, _ := ret[0].(error)
	return ret0
}

// NewShortURLBatch indicates an expected call of NewShortURLBatch.
func (mr *MockUseCaseMockRecorder) NewShortURLBatch(ctx, entities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewShortURLBatch", reflect.TypeOf((*MockUseCase)(nil).NewShortURLBatch), ctx, entities)
}

// NewUser mocks base method.
func (m *MockUseCase) NewUser(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewUser", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewUser indicates an expected call of NewUser.
func (mr *MockUseCaseMockRecorder) NewUser(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewUser", reflect.TypeOf((*MockUseCase)(nil).NewUser), ctx)
}

// Ping mocks base method.
func (m *MockUseCase) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockUseCaseMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockUseCase)(nil).Ping), ctx)
}

// ProcessShortURL mocks base method.
func (m *MockUseCase) ProcessShortURL(ctx context.Context, id string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessShortURL", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ProcessShortURL indicates an expected call of ProcessShortURL.
func (mr *MockUseCaseMockRecorder) ProcessShortURL(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessShortURL", reflect.TypeOf((*MockUseCase)(nil).ProcessShortURL), ctx, id)
}
