// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/georgg2003/shortener/internal/usecase (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination ./mock/mock.go -package mock . Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/georgg2003/shortener/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetLongURL mocks base method.
func (m *MockRepository) GetLongURL(ctx context.Context, shortID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLongURL", ctx, shortID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLongURL indicates an expected call of GetLongURL.
func (mr *MockRepositoryMockRecorder) GetLongURL(ctx, shortID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLongURL", reflect.TypeOf((*MockRepository)(nil).GetLongURL), ctx, shortID)
}

// GetShortID mocks base method.
func (m *MockRepository) GetShortID(ctx context.Context, originalURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShortID", ctx, originalURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShortID indicates an expected call of GetShortID.
func (mr *MockRepositoryMockRecorder) GetShortID(ctx, originalURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShortID", reflect.TypeOf((*MockRepository)(nil).GetShortID), ctx, originalURL)
}

// GetShortIDsBatch mocks base method.
func (m *MockRepository) GetShortIDsBatch(ctx context.Context, entities []*models.URLEntity) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShortIDsBatch", ctx, entities)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShortIDsBatch indicates an expected call of GetShortIDsBatch.
func (mr *MockRepositoryMockRecorder) GetShortIDsBatch(ctx, entities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShortIDsBatch", reflect.TypeOf((*MockRepository)(nil).GetShortIDsBatch), ctx, entities)
}

// GetUserURLs mocks base method.
func (m *MockRepository) GetUserURLs(ctx context.Context, userID int64) ([]models.URLEntity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserURLs", ctx, userID)
	ret0, _ := ret[0].([]models.URLEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserURLs indicates an expected call of GetUserURLs.
func (mr *MockRepositoryMockRecorder) GetUserURLs(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserURLs", reflect.TypeOf((*MockRepository)(nil).GetUserURLs), ctx, userID)
}

// NewShortURL mocks base method.
func (m *MockRepository) NewShortURL(ctx context.Context, url, shortID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewShortURL", ctx, url, shortID)
	ret0, _ := ret[0].(error)
	return ret0
}

// NewShortURL indicates an expected call of NewShortURL.
func (mr *MockRepositoryMockRecorder) NewShortURL(ctx, url, shortID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewShortURL", reflect.TypeOf((*MockRepository)(nil).NewShortURL), ctx, url, shortID)
}

// NewShortURLBatch mocks base method.
func (m *MockRepository) NewShortURLBatch(ctx context.Context, entities []*models.URLEntity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewShortURLBatch", ctx, entities)
	ret0, _ := ret[0].(error)
	return ret0
}

// NewShortURLBatch indicates an expected call of NewShortURLBatch.
func (mr *MockRepositoryMockRecorder) NewShortURLBatch(ctx, entities any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewShortURLBatch", reflect.TypeOf((*MockRepository)(nil).NewShortURLBatch), ctx, entities)
}

// NewUser mocks base method.
func (m *MockRepository) NewUser(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewUser", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewUser indicates an expected call of NewUser.
func (mr *MockRepositoryMockRecorder) NewUser(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewUser", reflect.TypeOf((*MockRepository)(nil).NewUser), ctx)
}

// Ping mocks base method.
func (m *MockRepository) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRepositoryMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRepository)(nil).Ping), ctx)
}
