// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/georgg2003/shortener/internal/repository/audit (interfaces: AuditRepository)
//
// Generated by this command:
//
//	mockgen -destination ./mock/mock.go -package mock . AuditRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	audit "github.com/georgg2003/shortener/internal/repository/audit"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditRepository is a mock of AuditRepository interface.
type MockAuditRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuditRepositoryMockRecorder
	isgomock struct{}
}

// MockAuditRepositoryMockRecorder is the mock recorder for MockAuditRepository.
type MockAuditRepositoryMockRecorder struct {
	mock *MockAuditRepository
}

// NewMockAuditRepository creates a new mock instance.
func NewMockAuditRepository(ctrl *gomock.Controller) *MockAuditRepository {
	mock := &MockAuditRepository{ctrl: ctrl}
	mock.recorder = &MockAuditRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditRepository) EXPECT() *MockAuditRepositoryMockRecorder {
	return m.recorder
}

// WriteLog mocks base method.
func (m *MockAuditRepository) WriteLog(arg0 audit.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteLog", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteLog indicates an expected call of WriteLog.
func (mr *MockAuditRepositoryMockRecorder) WriteLog(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteLog", reflect.TypeOf((*MockAuditRepository)(nil).WriteLog), arg0)
}
