// Code generated by go generate; DO NOT EDIT.
// This file was generated by reset/main.go

package models

func (rs *DeleteUserURLsTask) Reset() {
	if rs == nil {
		return
	}
	rs.ShortIDs = rs.ShortIDs[:0]
	rs.UserID = 0
}
