CREATE TABLE short_url (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  short_url VARCHAR(8) NOT NULL,
  long_url VARCHAR NOT NULL
);

CREATE INDEX idx_short_url_short_url ON short_url(short_url);
