CREATE TABLE url_entity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  short_id VARCHAR(8) NOT NULL UNIQUE,
  original_url VARCHAR NOT NULL
);

CREATE INDEX idx_url_entity_short_id ON url_entity(short_id);
