package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"io"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

type fieldReseter interface {
	GetClearInstructions(structName string) string
}

type resetableField struct {
	Name string
}

type resetableIntField struct {
	resetableField
}

func (i resetableIntField) GetClearInstructions(structName string) string {
	return fmt.Sprintf("%s.%s = 0", structName, i.Name)
}

type resetableBoolField struct {
	resetableField
}

func (i resetableBoolField) GetClearInstructions(structName string) string {
	return fmt.Sprintf("%s.%s = false", structName, i.Name)
}

type resetableStrField struct {
	resetableField
}

func (i resetableStrField) GetClearInstructions(structName string) string {
	return fmt.Sprintf(`%s.%s = ""`, structName, i.Name)
}

type resetablePtrField struct {
	resetableField
}

func (i resetablePtrField) GetClearInstructions(structName string) string {
	return fmt.Sprintf("%s.%s = nil", structName, i.Name)
}

type resetableSliceField struct {
	resetableField
}

func (i resetableSliceField) GetClearInstructions(structName string) string {
	fieldName := fmt.Sprintf("%s.%s", structName, i.Name)
	return fmt.Sprintf(`%[1]s = %[1]s[:0]`, fieldName)
}

type resetableMapField struct {
	resetableField
}

func (i resetableMapField) GetClearInstructions(structName string) string {
	return fmt.Sprintf("clear(%s.%s)", structName, i.Name)
}

type resetableChildField struct {
	resetableField
}

func (i resetableChildField) GetClearInstructions(structName string) string {
	fieldName := fmt.Sprintf("%s.%s", structName, i.Name)
	return fmt.Sprintf(`
		if resetter, ok := %[1]s.(interface{ Reset() }); ok && %[1]s != nil {
			resetter.Reset()
		}
	`, fieldName)
}

type resetableStruct struct {
	Name   string
	Fields []fieldReseter
}

type resetablePkg struct {
	Name    string
	Structs []resetableStruct
}

const temlateText = `
// Code generated by go generate; DO NOT EDIT.
// This file was generated by reset/main.go

package {{ .Name }}

{{- range .Structs }}
func (rs *{{ .Name }}) Reset() {
	if rs == nil {
		return
	}

	{{- range .Fields }}
		{{ .GetClearInstructions "rs" -}}
	{{- end }}
}
{{- end }}
`

var t = template.Must(template.New("reset").Parse(temlateText))

func getReseter(name string, expr ast.Expr) fieldReseter {
	base := resetableField{Name: name}

	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
			"float32", "float64", "byte", "rune":
			return resetableIntField{base}
		case "string":
			return resetableStrField{base}
		case "bool":
			return resetableBoolField{base}
		default:
			return resetableChildField{base}
		}

	case *ast.StarExpr:
		return resetablePtrField{resetableField: base}

	case *ast.ArrayType:
		return resetableSliceField{base}

	case *ast.MapType:
		return resetableMapField{base}

	case *ast.SelectorExpr, *ast.InterfaceType:
		return resetableChildField{base}

	default:
		return nil
	}
}

func processFile(file *ast.File) []resetableStruct {
	var structs []resetableStruct

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			fullText := genDecl.Doc.Text() + typeSpec.Doc.Text() + typeSpec.Comment.Text()
			if !strings.Contains(fullText, "generate:reset") {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			resStruct := resetableStruct{Name: typeSpec.Name.Name}

			for _, field := range structType.Fields.List {
				for _, nameIdent := range field.Names {
					if reseter := getReseter(nameIdent.Name, field.Type); reseter != nil {
						resStruct.Fields = append(resStruct.Fields, reseter)
					}
				}
				if len(field.Names) == 0 {
					typeName := ""
					if ident, ok := field.Type.(*ast.Ident); ok {
						typeName = ident.Name
					}
					if reseter := getReseter(typeName, field.Type); reseter != nil {
						resStruct.Fields = append(resStruct.Fields, reseter)
					}
				}
			}
			structs = append(structs, resStruct)
		}
	}

	return structs
}

func processPackage(pkg *packages.Package) error {
	var structs []resetableStruct
	for _, file := range pkg.Syntax {
		structs = append(structs, processFile(file)...)
	}

	if len(structs) == 0 {
		return nil
	}

	resPkg := resetablePkg{
		Name:    pkg.Name,
		Structs: structs,
	}

	var buf bytes.Buffer
	err := t.Execute(&buf, resPkg)
	if err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	bytes, err := io.ReadAll(&buf)
	if err != nil {
		return fmt.Errorf("failed to read buffer: %w", err)
	}

	fmtBytes, err := format.Source(bytes)
	if err != nil {
		return fmt.Errorf("failed to format bytes: %w", err)
	}

	filename := filepath.Join(pkg.Dir, "reset.gen.go")
	if err = os.WriteFile(filename, fmtBytes, 0644); err != nil {
		return fmt.Errorf("failed to write file in %s: %w", pkg.Dir, err)
	}

	return nil
}

func main() {
	path := flag.String("path", "./...", "files directory")
	flag.Parse()

	cfg := &packages.Config{
		Mode:  packages.NeedFiles | packages.NeedSyntax | packages.NeedName,
		Tests: false,
	}

	pkgs, err := packages.Load(cfg, *path)
	if err != nil {
		log.Fatalf("failed to load packages %v", err)
	}

	for _, pkg := range pkgs {
		if err := processPackage(pkg); err != nil {
			log.Printf("failed to process package %s: %v", pkg.Name, err)
		}
	}
}
