package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
	"golang.org/x/tools/imports"
)

type fieldReseter interface {
	GetClearInstructions(accessor string) string
}

type rootField struct {
	Name    string
	Reseter fieldReseter
}

func (rf rootField) Render(receiverName string) string {
	accessor := fmt.Sprintf("%s.%s", receiverName, rf.Name)
	return rf.Reseter.GetClearInstructions(accessor)
}

type resetableIntField struct{}

func (i resetableIntField) GetClearInstructions(acc string) string { return fmt.Sprintf("%s = 0", acc) }

type resetableBoolField struct{}

func (i resetableBoolField) GetClearInstructions(acc string) string {
	return fmt.Sprintf("%s = false", acc)
}

type resetableStrField struct{}

func (i resetableStrField) GetClearInstructions(acc string) string {
	return fmt.Sprintf("%s = \"\"", acc)
}

type resetableSliceField struct{}

func (i resetableSliceField) GetClearInstructions(acc string) string {
	return fmt.Sprintf("%[1]s = %[1]s[:0]", acc)
}

type resetableMapField struct{}

func (i resetableMapField) GetClearInstructions(acc string) string {
	return fmt.Sprintf("clear(%s)", acc)
}

type resetablePtrField struct {
	field fieldReseter
}

func (i resetablePtrField) GetClearInstructions(acc string) string {
	inner := fmt.Sprintf("(*%s)", acc)
	return fmt.Sprintf("if %s != nil { %s }", acc, i.field.GetClearInstructions(inner))
}

type resetableResetCallField struct{}

func (i resetableResetCallField) GetClearInstructions(acc string) string {
	return fmt.Sprintf("%s.Reset()", acc)
}

type resetableZeroValueField struct {
	TypeName string
}

func (i resetableZeroValueField) GetClearInstructions(acc string) string {
	return fmt.Sprintf("%s = %s{}", acc, i.TypeName)
}

func hasResetMethod(t types.Type) bool {
	mSet := types.NewMethodSet(t)
	if mSet.Lookup(nil, "Reset") != nil {
		return true
	}
	pSet := types.NewMethodSet(types.NewPointer(t))
	return pSet.Lookup(nil, "Reset") != nil
}

func getReseter(t types.Type, info *types.Info, willHaveReset map[string]bool) fieldReseter {
	underlying := t.Underlying()

	if basic, ok := underlying.(*types.Basic); ok {
		bi := basic.Info()
		switch {
		case bi&types.IsInteger != 0 || bi&types.IsFloat != 0:
			return resetableIntField{}
		case bi&types.IsString != 0:
			return resetableStrField{}
		case bi&types.IsBoolean != 0:
			return resetableBoolField{}
		}
	}

	fullTypeName := t.String()
	parts := strings.Split(fullTypeName, ".")
	shortName := parts[len(parts)-1]

	if willHaveReset[shortName] || hasResetMethod(t) {
		return resetableResetCallField{}
	}

	switch u := underlying.(type) {
	case *types.Slice:
		return resetableSliceField{}
	case *types.Map:
		return resetableMapField{}
	case *types.Pointer:
		return resetablePtrField{field: getReseter(u.Elem(), info, willHaveReset)}
	case *types.Array, *types.Struct:
		typeName := types.TypeString(t, func(p *types.Package) string { return p.Name() })
		return resetableZeroValueField{TypeName: typeName}
	}

	return nil
}

const templateText = `// Code generated by go generate; DO NOT EDIT.
package {{ .PackageName }}

{{ range .Structs }}
func (rs *{{ .Name }}) Reset() {
  if rs == nil {
    return
  }
  {{ range .Fields }}
  {{ .Render "rs" }}
  {{- end }}
}
{{ end }}
`

var tmpl = template.Must(template.New("reset").Parse(templateText))

func main() {
	path := flag.String("path", "./...", "directory path")
	flag.Parse()

	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo,
	}

	pkgs, err := packages.Load(cfg, *path)
	if err != nil {
		log.Fatal(err)
	}

	for _, pkg := range pkgs {
		willHaveReset := make(map[string]bool)
		for _, file := range pkg.Syntax {
			for _, decl := range file.Decls {
				gen, ok := decl.(*ast.GenDecl)
				if !ok {
					continue
				}
				doc := ""
				if gen.Doc != nil {
					doc = gen.Doc.Text()
				}
				for _, spec := range gen.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					lineComment := ""
					if ts.Comment != nil {
						lineComment = ts.Comment.Text()
					}
					if strings.Contains(doc+lineComment, "generate:reset") {
						willHaveReset[ts.Name.Name] = true
					}
				}
			}
		}

		var structs []struct {
			Name   string
			Fields []rootField
		}

		for _, file := range pkg.Syntax {
			for _, decl := range file.Decls {
				gen, ok := decl.(*ast.GenDecl)
				if !ok {
					continue
				}
				for _, spec := range gen.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok || !willHaveReset[ts.Name.Name] {
						continue
					}

					st, ok := ts.Type.(*ast.StructType)
					if !ok {
						continue
					}

					resStruct := struct {
						Name   string
						Fields []rootField
					}{Name: ts.Name.Name}

					for _, field := range st.Fields.List {
						t := pkg.TypesInfo.TypeOf(field.Type)
						if len(field.Names) == 0 {
							fieldName := ""
							if ident, ok := field.Type.(*ast.Ident); ok {
								fieldName = ident.Name
							} else if star, ok := field.Type.(*ast.StarExpr); ok {
								if ident, ok := star.X.(*ast.Ident); ok {
									fieldName = ident.Name
								}
							}
							if fieldName != "" {
								if res := getReseter(t, pkg.TypesInfo, willHaveReset); res != nil {
									resStruct.Fields = append(resStruct.Fields, rootField{
										Name:    fieldName,
										Reseter: res,
									})
								}
							}
						}

						for _, name := range field.Names {
							if res := getReseter(t, pkg.TypesInfo, willHaveReset); res != nil {
								resStruct.Fields = append(resStruct.Fields, rootField{
									Name:    name.Name,
									Reseter: res,
								})
							}
						}
					}
					structs = append(structs, resStruct)
				}
			}
		}

		if len(structs) == 0 {
			continue
		}

		var buf bytes.Buffer
		tmpl.Execute(&buf, map[string]interface{}{
			"PackageName": pkg.Name,
			"Structs":     structs,
		})

		res, err := imports.Process(filepath.Join(pkg.Dir, "reset.gen.go"), buf.Bytes(), nil)
		if err != nil {
			res = buf.Bytes()
		}

		os.WriteFile(filepath.Join(pkg.Dir, "reset.gen.go"), res, 0644)
	}
}
